### ISSUE TITLE
Doesn't support composite sortkeys

### ISSUE THREAD

**Issue by neilsh** [openmail/redshift_show_create_table#6]
Currently the code denotes sortkey columns by adding a "SORTKEY" attribute on the line for the corresponding column. This works when there's just one sortkey, but doesn't work for composite/multiple sortkeys, which must be specified as a table attribute using the syntax "SORTKEY ( column_name [, ....])", listing the sortkeys in order of primary/secondary/etc. The sortkey order can be found in the PG_TABLE_DEF table:  http://docs.aws.amazon.com/redshift/latest/dg/r_PG_TABLE_DEF.html

For reference, trying to create a table with multiple sortkeys using the column-attribute (instead of table-attribute) syntax results in the following error: "too many SORTKEY declarations at column "COLUMN_NAME" of table "TABLE_NAME"

**Comment by CropCircleSys** [comment]
I've fixed this in https://github.com/openmail/redshift_show_create_table/pull/9
